export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
// export const ADM_SIGNIN_SUCCESS = 'ADM_SIGNIN_SUCCESS';
export const AUTH_SYSTEM_ERROR = 'AUTH_SYSTEM_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const SIGNOUT = 'SIGNOUT';
export const COOKIE_CHECKED = 'COOKIE_CHECKED';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';

